# Generated by Django 2.0.4 on 2018-04-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180426_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='view',
            new_name='views',
        ),
    ]
